name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Resolve SwiftPM dependencies
        run: swift package resolve

      - name: Archive the app
        run: xcodebuild \
            -workspace WhisperAX.xcodeproj/project.xcworkspace \
            -scheme WhisperAX \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
            archive -archivePath ./build/WhisperAX.xcarchive

      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath ./build/WhisperAX.xcarchive \
            -exportPath ./build \
            -exportOptionsPlist WhisperAX.xcodeproj/project.xcworkspace/ExportOptions.plist

      # Step 6: Upload the IPA artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: WhisperAX-ipa
          path: ./build/*.ipa
